#!/bin/bash
#*******************************************************************************
# ALMA - Atacama Large Millimeter Array
# Copyright (c) ESO - European Southern Observatory, 2011
# (in the framework of the ALMA collaboration).
# All rights reserved.
# 
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
# 
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Lesser General Public License for more details.
# 
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307  USA
#*******************************************************************************
# -*- ksh -*-

# $Id: testAll,v 1.3 2011/11/24 13:06:42 amanning Exp $
# 
# amchavan, 01-Feb-2006

# set -x

rm -f test.out test.err

acsStartJava -endorsed junit.textui.TestRunner 			\
		alma.ngas.client.NGAMSJClientTest		\
		1> ./test.out 2> ./test.err
if [ $? != 0 ] ; then
  echo "FAILED."
else
  echo "PASSED."
fi
